/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.java.test.fixtures.issue.repro;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
